### ISSUE TITLE
shoutem run-ios throws error on Mobile-Buy-SDK.

### ISSUE THREAD

**Issue by vinceprofeta** [shoutem/platform#13]
warning "react-native-shopify@0.2.4" has incorrect peer dependency "react-native@>=0.40.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 30.22s.
[running preBuild] - shoutem.application: 1.030ms
[running preBuild] - shoutem.auth: 0.825ms
preBuild: 135.140ms
Starting pods install
create extensions.js: 146.037ms
Analyzing dependencies
Fetching podspec for `ShoutemShopify` from `../node_modules/shoutem.shopify/ShoutemShopify.podspec`
[!] Unable to satisfy the following requirements:

- `Mobile-Buy-SDK (= 2.2.0)` required by `ShoutemShopify (1.0)`

None of your spec sources contain a spec satisfying the dependency: `Mobile-Buy-SDK (= 2.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
{ Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/vincentprofeta/.shoutem/production/client/8580/scripts/node_modules/superspawn/lib/index.js:172:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5) code: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @shoutem/mobile-app@0.56.2 configure: `node scripts/configure`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @shoutem/mobile-app@0.56.2 configure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SoHotSoup** [comment]
Hi! Thanks for submitting the issue, to fix it just run:
pod repo update

And try again 'shoutem run-ios'

**Comment by vinceprofeta** [comment]
@SoHotSoup thanks that worked!
