### ISSUE TITLE
Cannot  Link Extension. Error when building. Peer Dependancies in app/package.json Doesnt Exist. 

### ISSUE THREAD

**Issue by vinceprofeta** [shoutem/platform#15]
```shoutem run```  with custom extension linked throws an error. 

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3478): UnableToResolveError: Unable to resolve module react from /Users/vincentprofeta/Documents/personal/ShoutEm_Chat/volv-messanger/app/screens/Conversations.js: Module does not exist in the module map

"Notice that you didn’t need to install the @shoutem/ui package into the app folder of your extension. That’s because this package will be installed in the extension by the app into which your extension is bundled. All packages installed by the app by default can be found in peerDependencies of app/package.json."

My Screen Imports

```
import React, {
  Component
} from 'react';

import {
  TouchableOpacity,
} from 'react-native';

import {
  Image,
  ListView,
  Tile,
  Title,
  Subtitle,
  Overlay,
  Screen
} from '@shoutem/ui';

import { NavigationBar } from '@shoutem/ui/navigation';
import { navigateTo } from '@shoutem/core/navigation';
import { ext } from '../extension';
import { connect } from 'react-redux';
```

**Comment by vinceprofeta** [comment]
![image](https://user-images.githubusercontent.com/1517775/27508797-d39a2140-58b2-11e7-9af7-6817e801c15a.png)

**Comment by Vladimir-Vdovic** [comment]
At first glance, it seems you're using react-redux, but haven't installed it into your extension (and that way into the app) properly.

Check this quick tutorial from our documentation on how to [install 3rd party packages](http://shoutem.github.io/docs/extensions/tutorials/installing-3rd-party-packages).

Also, there's alternatives to `shoutem run`, you can check out our `Setting up your Local Environment` documentation for more info [here](http://shoutem.github.io/docs/extensions/tutorials/setting-local-environment).

Currently you can also use `shoutem run-ios` and `shoutem run-android`, which are analogous to `react-native run-ios` and `react-native run-android` which you are probably familiar with.

**Comment by vinceprofeta** [comment]
I installed react-redux, no luck... I have other dependancies in my package.json
```
"bluebird": "^3.5.0",
"fuse.js": "^3.0.5",
"react-native-gifted-chat": "0.0.10",
"react-redux": "^5.0.5",
"reselect": "^3.0.1",
"socket.io": "^1.7.4",
"superagent": "^3.5.2",
 "uuid": "^3.1.0"
```

After install react redux I started seeing this.

```(node:80821) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3830): UnableToResolveError: Unable to resolve module @shoutem/redux-io from /Users/vincentprofeta/Documents/personal/ShoutEm_Chat/volv-messanger/app/middleware.js: Module does not exist in the module map or in these directories:
Users/vincentprofeta/Documents/personal/ShoutEm_Chat/volv-messanger/app/node_modules/@shoutem```

I have been running ```shoutem run-ios```and not ```native run-ios```

**Comment by vinceprofeta** [comment]
@Vladimir-Vdovic
Is there a way for you to pull down the app and see if you can reproduce or help debug? The app runs fine when I publish to shoutem and run the app. The issue occurs when I link the package

**Comment by Vladimir-Vdovic** [comment]
I'll take a crack at it, see if I can't get it to work. It's a very confusing error, I'll make a note to get back to you once I try it out and see if I can fix it.

**Comment by danielmarston** [comment]
@Vladimir-Vdovic Any news on this? Any apps running locally with local linked extensions throw the error.

**Comment by Vladimir-Vdovic** [comment]
Issue has been resolved with new extension development flow detailed in our [documentation](https://shoutem.github.io/docs/extensions/tutorials/getting-started).
